<?
if(!$this->hasObjectToEdit()){
	echo  ("no hay objeto a editar ".__FILE__.'-'.__LINE__);
	return;
}
$x = $this->getObjectToEdit();

?><?if($this->getIdToEdit()):?>
<input type="hidden" name="tipo_punto[id]" value="<?=$x->getId()?>" /><!-- si esta a cero o vacio es agregar --><?endif;?>
<fieldset>
	<legend><?if(!$this->getIdToEdit()):?>Nuevo<?else:?>Editar<?endif;?> TipoPunto</legend>
	<fieldset>
		<h3>Datos</h3>
		<div>
			<label>Nombre: </label>
			<span><?
				$input = Core::getObject('Core_Html_Tag_Custom', 'input');
				$input
					->setType('text')
					->setMaxlength(300)
					->setId('nombre')
					->setName('tipo_punto[nombre]')
					->setValue($x->getNombre())
					->setData('data-campo', '<b>Nombre</b>')
					->setData('data-validator', '{empty:false}')
				;
				echo $input->getHtml();
			?> 
			</span>
			<h3>Imagenes</h3>
			<div style="display:inline;float:left;">
				<label>Imagen Normal: </label>
				<span><?
					$src_real = $src = $x->getImagenDeseleccionado();
					$src = $src?$this->getUrl($src):'';//$this->getSkinUrl('img/empty.gif');?> 
					<?php print $this->getImagenDeseleccionado(); ?> 
					<img class="show_image_deseleccionado" src="<?php print $src; ?>" />
					<input type="hidden" id="imagen_deseleccionado" name="tipo_punto[imagen_deseleccionado]" value="<?php print $src_real; ?>" data-campo="<?php print htmlentities('<b>Imagen Normal</b>');?>" data-mensaje="Debe seleccionar una imagen para %field" data-validator="{empty:false}" />
					<img class="addimg" data-wich="deseleccionado" src="<?php print $this->getSkinUrl('img/picture_search.png'); ?>" title="seleccionar imagen" />
					<input type="hidden" name="tipo_punto[imagen_deseleccionado_hotspot_x]" value="<?php print $x->getData('imagen_deseleccionado_hotspot_x'); ?>" />
					<input type="hidden" name="tipo_punto[imagen_deseleccionado_hotspot_y]" value="<?php print $x->getData('imagen_deseleccionado_hotspot_y'); ?>" />
				</span>
			</div>
			<div style="display:inline;float:left;padding:0 5px;margin:0 5px;border-right:thin dashed black;border-color:black;border-style:dashed;border-width:0 1px;margin:0 7px;padding:0 7px;">
				<label>Imagen Seleccionado: </label>
				<span><?
					$src_real = $src = $x->getImagenSeleccionado();
					$src = $src?$this->getUrl($src):'';//$this->getSkinUrl('img/empty.gif');?> 
					<?php print $this->getImagenSeleccionado(); ?> 
					<img class="show_image_seleccionado" src="<?php print $src; ?>" />
					<input type="hidden" id="imagen_seleccionado" name="tipo_punto[imagen_seleccionado]" value="<?php print $src_real; ?>" />
					<img class="addimg" data-wich="seleccionado" src="<?php print $this->getSkinUrl('img/picture_search.png'); ?>" title="seleccionar imagen" />
					<input type="hidden" name="tipo_punto[imagen_seleccionado_hotspot_x]" value="<?php print $x->getData('imagen_seleccionado_hotspot_x'); ?>" />
					<input type="hidden" name="tipo_punto[imagen_seleccionado_hotspot_y]" value="<?php print $x->getData('imagen_seleccionado_hotspot_y'); ?>" />
				</span>
			</div>
			<div style="display:inline;float:left;">
				<label>Imagen Over: </label>
				<span><?
					$src_real = $src = $x->getImagenOver();
					$src = $src?$this->getUrl($src):'';//$this->getSkinUrl('img/empty.gif');?> 
					<?php print $this->getImagenOver(); ?> 
					<img class="show_image_over" src="<?php print $src; ?>" />
					<input type="hidden" id="imagen_over" name="tipo_punto[imagen_over]" value="<?php print $src_real; ?>" />
					<img class="addimg" data-wich="over" src="<?php print $this->getSkinUrl('img/picture_search.png'); ?>" title="seleccionar imagen" />
					<input type="hidden" name="tipo_punto[imagen_over_hotspot_x]" value="<?php print $x->getData('imagen_over_hotspot_x'); ?>" />
					<input type="hidden" name="tipo_punto[imagen_over_hotspot_y]" value="<?php print $x->getData('imagen_over_hotspot_y'); ?>" />
				</span>
			</div>
		</div>
	</fieldset>
	<div class="controls">
		<?php print Core::getObject('Core_Html_Tag_Custom', 'input')->settype('submit')->setValue('Guardar')->getHtml(); ?>
	</div>
</fieldset>
<div style="display:none;">
	<div class="selectorHotSpot" style="text-align:center;">
		<div class="contenedorImagen" style="position:relative;float:left;">
			<img />
			<div class="hotspot" style="background-color:orange;position:absolute;top:0:left:0;"></div>
			<div class="hotspot_selected" style="background-color:red;position:absolute;top:0:left:0;"></div>
			<div class="tile" style="background-image:url(<?php print $this->getSkinUrl('img/5dotted.png'); ?>);height:100%;width:100%;position:absolute;top:0;left:0;"></div>
		</div>
		<div style="float:left;width:180px;text-align:left;">
			<b>Posicion X: </b><span class="show_hotspot_x"></span><br />
			<b>Posicion y: </b><span class="show_hotspot_y"></span><br />
		</div>
		<div style="clear:both;"></div>
		<input type="button" style="margin-left:50px;" onclick="javascript:jQuery.unblockUI();" value="cerrar" />
	</div>
</div>
<script>
var imagenes = ['seleccionado','deseleccionado','over'];
for(idx in imagenes){
	var wich = imagenes[idx];
	var xxx = 'window.onckfinder_'+wich+'=function(url){onckfinder(url,"'+wich+'");}';
	eval(xxx);
}
function onckfinder(url,wich){
	jQuery('#imagen_'+wich+'').val(url.split('<?php print $this->getUrl(); ?>').join(''));
	jQuery('.show_image_'+wich).attr('src', url).removeAttr('width');
}
jQuery(document).ready(function(){
	jQuery('.addimg').css('cursor','pointer').click(function(){
		var jqthis = jQuery(this);
		var wich = jqthis.attr('data-wich');
//		var funcion = 'onckfinder_'+wich;
//		//CKFinder.Popup('<?php print dirname($this->getSkinUrl('ckfinder/ckfinder.js')); ?>', null, null, funcion);
//		CKFinder.Popup({
//			SelectFunction:funcion,
//			ResourceType:'TipoPunto',
//			BasePath:'<?php print dirname($this->getSkinUrl('ckfinder/ckfinder.js')); ?>'
//		});
		var finder = new CKFinder();
		finder.resourceType = 'TipoPunto';
		finder.basePath = '<?php print dirname($this->getSkinUrl('ckfinder/ckfinder.js')); ?>';
		finder.selectActionFunction = function(url, data){
			return onckfinder(url,wich,data);
		};
		finder.popup();
			//'<?php print dirname($this->getSkinUrl('ckfinder/ckfinder.js')); ?>', null, null, funcion);
		try{
			//ckFinderBrowseServer('', $(this).attr('id'), 'ckFinderAppendImageField', 'ckFinderShowThumbnails');
		}
		catch(e){alert(e);}
		return(false);
	});


	jQuery('[class^=show_image_]').each(function(){
		this.image_empty_src = '<?php print $image_empty_src; ?>';
		this.image_empty_size = <?php print $image_empty_size+0; ?>; 
		var jqthis = jQuery(this);
		var jqimage = jqthis;
		var jqpapa = jqthis.parents('div:first');
		var jqinput = jQuery('input:eq(0)', jqpapa);
		var jqinput_hotspot_x = jQuery('input:eq(1)', jqpapa);
		var jqinput_hotspot_y= jQuery('input:eq(2)', jqpapa);
		jqpapa.css('position','relative');
		var jqdelete = jQuery('<div class="toolbox" style="cursor:pointer;display:none;position:absolute;bottom:0;width:16px;height:16px;background-image:url(\'<?php print $this->getSkinUrl('img/delete2.png'); ?>\')"></div>');
		jqpapa.append(jqdelete);
		var jqedit = jQuery('<div class="toolbox" style="cursor:pointer;display:none;position:absolute;bottom:0;margin-left:16px;width:16px;height:16px;background-image:url(\'<?php print $this->getSkinUrl('img/16x16/pencil.png'); ?>\')"></div>');
		jqpapa.append(jqedit);
		var jqtoolbox = jQuery('.toolbox', jqpapa);
		jqdelete.click(function(){
			jqimage.attr('src',jqimage[0].image_empty_src);
			jqimage.attr('width', jqimage[0].image_empty_size);
			jqinput.val('');
			jQuery(this).hide();
		});
		jqedit.click(function(){
			var pixel_size = 5;
			var width = parseInt(jqimage.width()) * pixel_size;
			var height = parseInt(jqimage.height()) * pixel_size;
			var jqselectorHotSpot = jQuery('.selectorHotSpot');
			var jqshow_hotspot_x = jQuery('.selectorHotSpot .show_hotspot_x');
			var jqshow_hotspot_y = jQuery('.selectorHotSpot .show_hotspot_y');
			var jqhotspot_selected = jQuery('.selectorHotSpot .hotspot_selected').width(pixel_size).height(pixel_size);
			var jqhotspot = jQuery('.selectorHotSpot .hotspot').width(pixel_size).height(pixel_size);
			var jqcontenedor_imagen = jQuery('.selectorHotSpot .contenedorImagen').width(width).height(height).css('cursor','default');
			jQuery('.selectorHotSpot img')
				.attr('src', jqimage.attr('src'))
				.width(width).height(height)
			;
			var begin_x = parseInt(jqinput_hotspot_x.val());
			var begin_y = parseInt(jqinput_hotspot_y.val());
			jqhotspot_selected.css('left', begin_x * pixel_size);
			jqhotspot_selected.css('top', begin_y * pixel_size);
			jQuery('.selectorHotSpot .tile')
				.unbind('mousemove')
				.mousemove(function(e){
					var posicion_x = e.layerX||e.offsetX;//firefox:ie
					var posicion_y = e.layerY||e.offsetY;//firefox:ie
					var discrete_x = parseInt(posicion_x/pixel_size);
					var discrete_y = parseInt(posicion_y/pixel_size);
					jqhotspot.css('left', discrete_x * pixel_size);
					jqhotspot.css('top', discrete_y * pixel_size);
					jqshow_hotspot_x.text(discrete_x);
					jqshow_hotspot_y.text(discrete_y);
				})
				.click(function(e){
					var posicion_x = e.layerX||e.offsetX;//firefox:ie
					var posicion_y = e.layerY||e.offsetY;//firefox:ie
					var discrete_x = parseInt(posicion_x/pixel_size);
					var discrete_y = parseInt(posicion_y/pixel_size);
					jqhotspot_selected.css('left', discrete_x * pixel_size);
					jqhotspot_selected.css('top', discrete_y * pixel_size);
					jqinput_hotspot_x.val(discrete_x);
					jqinput_hotspot_y.val(discrete_y);
				})
			;
			jQuery.blockUI({
				message:jqselectorHotSpot
			});
		});
		
		//alert(jqimage.attr('src'));
		var curr_src = jqimage.attr('src');
		if(curr_src=='' || curr_src==null){
			jqclear.click();
		}
		jqthis.timemouse({
			mouseover: function(){
				if(jqimage[0].image_empty_src == jqimage.attr('src')){
					return;
				}
				jqtoolbox.show();
			},
			mouseout: function(){
				jqtoolbox.hide();
			}, 
			time: 1600
		})
		;

	});
})
function validar_agregar_tipo_punto(formData, jqForm, options) {
	if(!validar(true)){
		return false;
	}
	return(true);
}
</script>