<?
	//$classnames = array('contenedor_main');
	$classnames = array();
	if($html_class = $this->getHtmlClass())
		$classnames[] = $html_class;
	if($this->hasClassnames()){
		$classnames[] = implode(' ', $this->getClassnames());
	}
	$classnames[] = implode(' ', Core_App::getLayout()->getActions());
	$classnames = implode(' ', $classnames);
	$classnames = $classnames?' class="'.$classnames.'"':'';
?>
<div <?=$classnames?>>
	<?=$this->getChildHtml('contenedor_main')?><?
		if($right = $this->getChildHtml('contenedor_right')){?> 
	<div class="contenedor_right"><?=$right?></div>
		<?	
		}
	?> 
</div>