<?
if(!$this->hasObjectToEdit()){
	echo  ("no hay objeto a editar ".__FILE__.'-'.__LINE__);
	return;
}
$x = $this->getObjectToEdit();

?><?if($this->getIdToEdit()):?>
<input type="hidden" name="resultado_esperado[id]" value="<?=$x->getId()?>" /><!-- si esta a cero o vacio es agregar --><?endif;?>
<fieldset id="<?php print $id_fielset = $this->generateRandomId(); ?>">
	<legend><?if(!$this->getIdToEdit()):?>Nuevo<?else:?>Editar<?endif;?> ResultadoEsperado</legend>
	<fieldset>
		<h3>Informacion de ResultadoEsperado</h3>
		<div>
			<label>Objetivo: </label>
			<span><?
				$objetivo = new Inta_Model_Objetivo();
				$objetivos = $objetivo->search();
				$html_select = '';
				foreach($objetivos as $objetivo){
					$option = c(Core::getObject('Core_Html_Tag_Custom', 'option'))
						->setValue($objetivo->getId())
						->setInnerHtml($objetivo->getNombre())
					;
					if($objetivo->getId()==$x->getIdObjetivo())
						$option->setSelected('selected');
					$html_select .= $option->getHtml();
				}
				echo c(Core::getObject('Core_Html_Tag_Custom', 'select'))
					->setName('resultado_esperado[id_objetivo]')
					->setId('id_objetivo')
					//->setDisabled('disabled')
					->setInnerHtml($html_select)
					->getHtml()
				;
			?> 
			</span>
			<label>Descripcion: </label>
			<span><?
				$input = Core::getObject('Core_Html_Tag_Custom', 'textarea');
				$input
					->setMaxlength(300)
					->setType('textarea')
					->setId('descripcion')
					->setName('resultado_esperado[descripcion]')
					->setInnerHtml(htmlentities(stripslashes($x->getDescripcion())))
					->setData('data-campo', '<b>Descripcion</b>')
					->setData('data-validator', '{empty:false}')
				;
				echo $input->getHtml();
			?> 
			</span>
			<div>
		</div>
		</div>
	</fieldset>
	<div class="controls">
		<?php if(in_array('entity_new',$this->getLayout()->getActions())): ?> 
		<input type="submit" value="Continuar"/>
		<?php else: ?> 
		<?php print Core::getObject('Core_Html_Tag_Custom', 'input')->settype('submit')->setValue('Guardar')->getHtml(); ?>
		<?php endif; ?> 
	</div>
</fieldset>
<script>

jQuery(document).ready(function(){
	jQuery('#descripcion').ckeditor();
});

function validar_agregar_resultado_esperado_datos(formData, jqForm, options) {
	jQuery('#descripcion').ckeditor('refresh');
	if(!validar_estatico_en('#<?php print $id_fielset; ?>')){
		tabpanelfocus(jQuery('#<?php print $id_fielset; ?>'));
		return false;
	}
	return(true);
}
</script>