<?
$messages = Core_App::getMessages('loginerror');
?>
<div id="content" class="clearfix">
  <div id="login_top">
    <div class="content">
      <div class="left">
        <div class="logo"><img src="<?php print $this->getSkinUrl('legacy/img/logo.jpg'); ?>" title="Logotipo INTA"></div>
        <div class="logo_title">Aplicaciones INTA - Marcos Juarez</div>
        <div class="logo_subtitle">Version Beta</div>
      </div>
    </div>
  </div>

  <div id="login_bottom">
    <div class="content">
      <div class="right">
        <div class="title_login">Ingreso al sistema</div>
        
        <form name="form1" method="post" >
          <input name="josso_cmd" value="login" type="hidden">
          <div class="form_row">
            <label class="name">Usuario:</label>
            <input name="username" class="text" type="text">
          </div>
          <div class="form_row">
            <label class="password">Contrase&ntilde;a: </label>
            <input name="password" value="" class="text error" type="password">
          </div>
          <div class="form_row actions_row">
            <input value="Ingresar" name="commit" class="button" type="submit">
          </div>
        </form>
        <center><?php if($messages)
	foreach($messages as $message){?> 
	<b><?=$message?></b><?	
	}?></center>
<script type="text/javascript" language="JavaScript">
  <!--
  var focusControl = document.forms["usernamePasswordLoginForm"].elements["josso_username"];

  if (focusControl.type != "hidden") {
     focusControl.focus();
  }
  // -->
</script>

      </div>
      <?/** /?>
      <div class="form_footer">
DNA SICyC | INTA<br>
<a href="http://intranet.inta.gov.ar/gestion_usuarios">No dispone de cuenta de usuario único</a><br>
	<a href="http://intranet.inta.gov.ar/gestion_usuarios">¿Olvido su contraseña?</a>
	</div>
<a href="http://intranet.inta.gov.ar/gestion_usuarios">    </a></div>
<a href="http://intranet.inta.gov.ar/gestion_usuarios">  </a></div>


<a href="http://intranet.inta.gov.ar/gestion_usuarios">    </a></div>
	<?/**/?>
<?
return;
$messages = Core_App::getMessages('loginerror');

?>
<fieldset style="width:50%; margin-top:170px;">
<legend>Ingreso al Sistema</legend><?
	if($messages)
	foreach($messages as $message){?> 
	<b><?=$message?></b><?	
	}
?> 
<form name="form1" method="post" >
<span class="oneField">
    <label for="user" class="preField">Usuario</label>
    <input name="username" type="text" class="required" id="user" value="" size="" />
    <span class="reqMark">*</span><br />
</span>

<span class="oneField">
    <label for="pass" class="preField">Password</label>

    <input name="password" type="password" class="required" id="pass" value="" size="" />
    <span class="reqMark">*</span><br />
</span>

<span class="oneField">
    <label class="loginN"></label>
</span>

<input name="btn_login" type="submit" id="btn_login" value="Entrar">
</form>
</fieldset>
