<?
if(!$this->hasObjectToEdit()){
	echo  ("no hay objeto a editar ".__FILE__.'-'.__LINE__);
	return;
}
$x = $this->getObjectToEdit();

?>
<div id="<?php print $id_control = $this->generateRandomId(); ?>">
<?if($this->getIdToEdit()):?>
<input type="hidden" name="resultado_esperado[id]" value="<?=$x->getId()?>" /><!-- si esta a cero o vacio es agregar --><?endif;?>
<fieldset id="<?php print $id_fielset = $this->generateRandomId(); ?>">
	<legend><?if(!$this->getIdToEdit()):?>Nuevo<?else:?>Editar<?endif;?> ResultadoEsperado</legend>
	<fieldset>
		<div>
				<div class="indicadores_resultado"><?
					if(!($indicadores = $x->getIndicadores())){
						echo '<div class="fila">'.$fila_indicador.'</div>';
					}
					else{
						$block_vista_indicador = $this->getChild('ver_indicador_resultado_esperado');
						echo '<ul>';
						foreach($indicadores as $indicador_resultado){
							$block_vista_indicador->setObjectToEdit(1);
							echo $block_vista_indicador->toHtml();
						}
						echo '</ul>';
					}
				?>
				</div> 
			<div style="padding-left:16px;height:auto;width:auto;background-repeat:no-repeat;background-position:0 50%" class="btn_agregar">Agregar Indicador</div>
		</div>
	</fieldset>
	<?/** /?>
	<div class="controls">
		<input type="submit" value="Guardar"/>
	</div>
	<?/**/?>
</fieldset>
<script>
jQuery(document).ready(function(){
	//jQuery('#descripcion').ckeditor();
	var jqform = jQuery('#<?php print $id_fielset; ?>');
	jQuery('.btn_agregar')
		.css('cursor','pointer')
		.click(function(){
			var jqwait = jQuery('<div></div>');
			jqwait.html('<center>Aguarde un momento ... <br /><img src="<?php print $this->getSkinUrl('img/loading.gif'); ?>" /></center>');
			jqwait.ScreenBlock();
			jQuery.get(
				'<?php print 'administrator/ajax/resultado_esperado/addEditIndicador/'.$x->getId().'/'; ?>',
				{
					target: '#'+jQuery('#<?php print $id_control; ?>').parents('.ui-tabs-panel:first').attr('id')
				},
				function (data){
					var jqwindow = jQuery('<div></div>');//.width(1024).height(300);
					jqwindow.ScreenBlock({autocenter:false,message_css:{top:'90px',left:'240px'}});
					jqwindow.html(data);
				}
			);
		})
	;
});

function validar_agregar_resultado_esperado_indicadores(formData, jqForm, options) {
	
	if(!validar_estatico_en('#<?php print $id_fielset; ?>')){
		tabpanelfocus(jQuery('#<?php print $id_fielset; ?>'));
		return false;
	}
	return(true);
}
</script>
</div>