<?
if(!$this->hasObjectToEdit()){
	echo  ("no hay objeto a editar ".__FILE__.'-'.__LINE__);
	return;
}
$x = $this->getObjectToEdit();

$image_empty_src = $this->getSkinUrl('img/empty.gif');
$image_empty_size = 42;

?><?if($this->getIdToEdit()):?>
<input type="hidden" name="audiencia[id]" value="<?=$x->getId()?>" /><!-- si esta a cero o vacio es agregar --><?endif;?>
<fieldset id="<?php print $id_fielset = $this->generateRandomId(); ?>">
	<legend><?if(!$this->getIdToEdit()):?>Nuevo<?else:?>Editar<?endif;?> Problema</legend>
	<fieldset>
		<h3>Informacion de Problema</h3>
		<div>
			<label>Audiencia: </label>
			<span><?
				$audiencia = new Inta_Model_Audiencia();
				$audiencias = $audiencia->search();
				$html_select = '';
				foreach($audiencias as $audiencia){
					$option = c(new Core_Html_Tag_Custom('option'))
						->setValue($audiencia->getId())
						->setInnerHtml($audiencia->getNombre())
					;
					if($audiencia->getId()==$x->getIdAudiencia())
						$option->setSelected('selected');
					$html_select .= $option->getHtml();
				}
				echo c(new Core_Html_Tag_Custom('select'))
					->setName('problema[id_audiencia]')
					->setId('id_audiencia')
					->setInnerHtml($html_select)
					->getHtml()
				;
			?> 
			</span>
			<label>Nombre: </label>
			<span><?
				$input = new Core_Html_Tag_Custom('input');
				$input
					->setMaxlength(300)
					->setType('text')
					->setId('nombre')
					->setName('problema[nombre]')
					->setValue($x->getNombre())
					->setData('data-campo', '<b>Nombre</b>')
					->setData('data-validator', '{empty:false}')
				;
				echo $input->getHtml();
			?> 
			</span>
			<label>Importancia Econ&oacute;mica: </label>
			<span><?
				$input = new Core_Html_Tag_Custom('input');
				$input
					->setMaxlength(300)
					->setType('text')
					->setId('importancia_economica')
					->setName('problema[importancia_economica]')
					->setValue($x->getImportanciaEconomica())
					->setData('data-campo', '<b>Importancia Econ&oacute;mica:</b>')
					->setData('data-validator', '{empty:false,entero:1}')
				;
				echo $input->getHtml();
			?> 
			</span>
			<label>Impacto Ambiental: </label>
			<span><?
				$input = new Core_Html_Tag_Custom('input');
				$input
					->setMaxlength(300)
					->setType('text')
					->setId('impacto_ambiental')
					->setName('problema[impacto_ambiental]')
					->setValue($x->getImpactoAmbiental())
					->setData('data-campo', '<b>Impacto Ambiental:</b>')
					->setData('data-validator', '{empty:false,entero:1}')
				;
				echo $input->getHtml();
			?> 
			</span>
			<label>Importancia Social: </label>
			<span><?
				$input = new Core_Html_Tag_Custom('input');
				$input
					->setMaxlength(300)
					->setType('text')
					->setId('importancia_social')
					->setName('problema[importancia_social]')
					->setValue($x->getImportanciaSocial())
					->setData('data-campo', '<b>Importancia Social:</b>')
					->setData('data-validator', '{empty:false,entero:1}')
				;
				echo $input->getHtml();
			?> 
			</span>
			<label>Familias Implicadas: </label>
			<span><?
				$input = new Core_Html_Tag_Custom('input');
				$input
					->setMaxlength(300)
					->setType('text')
					->setId('familias_implicadas')
					->setName('problema[familias_implicadas]')
					->setValue($x->getFamiliasImplicadas())
					->setData('data-campo', '<b>Familias Implicadas:</b>')
					->setData('data-validator', '{empty:false,entero:1}')
				;
				echo $input->getHtml();
			?> 
			</span>
			<label>Valor Agregado Potencial: </label>
			<span><?
				$input = new Core_Html_Tag_Custom('input');
				$input
					->setMaxlength(300)
					->setType('text')
					->setId('valor_agregado_potencial')
					->setName('problema[valor_agregado_potencial]')
					->setValue($x->getValorAgregadoPotencial())
					->setData('data-campo', '<b>Valor Agregado Potencial:</b>')
					->setData('data-validator', '{empty:false,entero:1}')
				;
				echo $input->getHtml();
			?> 
			</span>
			<label>Impacto de Desarrollo del Territorio: </label>
			<span><?
				$input = new Core_Html_Tag_Custom('input');
				$input
					->setMaxlength(300)
					->setType('text')
					->setId('impacto_desarrollo')
					->setName('problema[impacto_desarrollo]')
					->setValue($x->getImpactoDesarrollo())
					->setData('data-campo', '<b>Impacto de Desarrollo del Territorio:</b>')
					->setData('data-validator', '{empty:false,entero:1}')
				;
				echo $input->getHtml();
			?> 
			</span>
			<div>
		</div>
		</div>
	</fieldset>
	<div class="controls">
		<input type="submit" value="Guardar"/>
	</div>
</fieldset>
<script>

jQuery(document).ready(function(){

});

function validar_agregar_problema_datos(formData, jqForm, options) {
	if(!validar_estatico_en('#<?php print $id_fielset; ?>')){
		tabpanelfocus(jQuery('#<?php print $id_fielset; ?>'));
		return false;
	}
	return(true);
}
</script>