<?
if(!$this->hasObjectToEdit()){
	echo  ("no hay objeto a editar ".__FILE__.'-'.__LINE__);
	return;
}
$x = $this->getObjectToEdit();


//$dias = array(
//	'lunes','martes','miercoles','jueves','viernes','sabado','domingo'
//);
$dias = Granguia_Model_HorarioAnuncio::getDias();
$campos = array(
	'hora_inicio1'=>'Hora Inicio',
	'hora_fin1'=>'Hora Fin',
	'hora_inicio2'=>'Hora Inicio',
	'hora_fin2'=>'Hora Fin',
);
?>
<fieldset id="<?php print $id_fielset = $this->generateRandomId(); ?>">
	<input type="hidden" name="horario[id]" value="<?=$x->getId()?>" />
	<legend><?if(!$this->getIdToEdit()):?>Nuevo<?else:?>Editar<?endif;?> Anuncio</legend>
	<fieldset>
		<h3>Horarios laborables</h3>
		<table>
			<thead>
				<tr>
					<th>Horario/D&iacute;a</th>
					<th>Lunes</th>
					<th>Martes</th>
					<th>Mi&eacute;rcoles</th>
					<th>Jueves</th>
					<th>Viernes</th>
					<th>S&aacute;bado</th>
					<th>Domingo</th>
				</tr>
			</thead>
			<tbody><?php 
			
			foreach($campos as $field_prefix=>$label){ ?> 
				<tr>
				<th><?php print htmlentities($label); ?></th><?php 
				foreach($dias as $dia){?> 
				<td><?php 
					$fieldname = $field_prefix.'_'.$dia;
					echo c($input = Core::getObject('Core_Html_Tag_Custom', 'input'))
						->setType('text')
						->setMaxlength(5)
						->setSize(5)
						//->setId('label_contacto')
						->setName('horario['.$fieldname.']')
						->setValue($x->getData($fieldname))
						->setData('data-campo', '<b>'.htmlentities($label).' '.$dia.'</b>')
						->setData('data-validator', '{hora:true}')
						->getHtml()
					;
				?></td><?
				}?> 
				</tr><?
			}?> 
			</tbody>
		</table>
	</fieldset>
	<div class="controls">
		<?php print Core::getObject('Core_Html_Tag_Custom', 'input')->settype('submit')->setValue('Guardar')->getHtml(); ?>
	</div>
</fieldset>
<style>
#<?php print $id_fielset; ?>  table{
	border-collapse:collapse;
	
}
#<?php print $id_fielset; ?>  thead tr th{
	border:1px solid black;
	border-top:0px none;
	
}
#<?php print $id_fielset; ?>  tbody tr td{
	border:1px solid black;
	border-bottom:0;
	border-top:0;
	padding:0 5px;
	text-align:center;
}
#<?php print $id_fielset; ?>  tbody tr th{
	text-align:left;
}
</style>
<script>

jQuery(document).ready(function(){
});
function validar_agregar_horario_anuncio_contacto(formData, jqForm, options) {
	if(!validar_estatico_en('#<?php print $id_fielset; ?>')){
		tabpanelfocus(jQuery('#<?php print $id_fielset; ?>'));
		return false;
	}
	return(true);
}
</script>