<?
if(!$this->hasObjectToEdit()){
	echo  ("no hay objeto a editar ".__FILE__.'-'.__LINE__);
	return;
}
$x = $this->getObjectToEdit();

$image_empty_src = $this->getSkinUrl('img/empty.gif');
$image_empty_size = 42;
?>
<fieldset id="<?php print $id_fielset = $this->generateRandomId(); ?>">
	<legend><?if(!$this->getIdToEdit()):?>Nuevo<?else:?>Editar<?endif;?> Anuncio</legend>
<?

	if($opciones_nodo = $this->appendBlock('<opciones_nodo />'))
	echo $opciones_nodo
		->setIdNodo($x->getIdNodo())
		->setFuncionValidadora('validar_agregar_anuncio_nodo_opciones')
		->getHtml()
	;

?>
	<div class="controls">
		<?php print Core::getObject('Core_Html_Tag_Custom', 'input')->settype('submit')->setValue('Guardar')->getHtml(); ?>
	</div>
</fieldset>
<script>
function validar_agregar_anuncio_nodo(formData, jqForm, options) {
	if(!validar_estatico_en('#<?php print $id_fielset; ?>')){
		tabpanelfocus(jQuery('#<?php print $id_fielset; ?>'));
		return false;
	}
	return(true);
}
</script>