<?
if(!$this->hasObjectToEdit()){
	echo  ("no hay objeto a editar ".__FILE__.'-'.__LINE__);
	return;
}
$x = $this->getObjectToEdit();

$image_empty_src = $this->getSkinUrl('img/empty.gif');
$image_empty_size = 42;
?>
<fieldset id="<?php print $id_fielset = $this->generateRandomId(); ?>">
	<legend><?if(!$this->getIdToEdit()):?>Nuevo<?else:?>Editar<?endif;?> Anuncio</legend>
	<fieldset>
		<h3>Formulario de contacto</h3>
		<div>
			<label>Tipo: </label>
			<span><?
				$select = Core::getObject('Core_Html_Tag_Custom', 'select');
				$select
					//->setMaxlength(300)
					//->setType('text')
					->setId('id_tipo_contacto')
					->setName('anuncio[id_tipo_contacto]')
					//->setValue($x->getNombre())
					//->setData('data-campo', '<b>Nombre</b>')
					//->setData('data-validator', '{empty:false}')
				;
				$html = '';
				if($this->hasTiposContactos())
					foreach($this->getTiposContactos() as $tipo){
						$option = Core::getObject('Core_Html_Tag_Custom', 'option');
						$option
							->setValue($tipo->getId())
							->setInnerHtml($tipo->getNombre())
						;
						if($tipo->getId()==$x->getIdTipoContacto())
							$option->setSelected('selected');
						$html .= $option->getHtml();
					}
				echo $select
					->setInnerHtml($html)
					->getHtml()
				;
			?> 
			</span>
		</div>
		<div>
			<label>Etiqueta del enlace: </label>
			<span><?
				$input = Core::getObject('Core_Html_Tag_Custom', 'input');
				$input
					->setType('text')
					->setMaxlength(50)
					->setId('label_contacto')
					->setName('anuncio[label_contacto]')
					->setValue($x->getLabelContacto())
					//->setData('data-campo', '<b>Email</b>')
					//->setData('data-validator', '{empty:false}')
				;
				echo $input->getHtml();
			?> 
			</span>
		</div>
		<div>
			<label>Texto del formulario: </label>
			<span><?
				$input = Core::getObject('Core_Html_Tag_Custom', 'textarea');
				$input
					//->setType('text')
					//->setMaxlength(255)
					->setId('texto_contacto')
					->setName('anuncio[texto_contacto]')
					->setRows(7)
					//->setValue($x->getTextoContacto())
					->setData('data-campo', '<b>Texto de Contacto</b>')
					->setData('data-validator', '{empty:false}')
					->setInnerHtml(htmlentities($x->getTextoContacto()))
				;
				echo $input->getHtml();
			?> 
			</span>
		</div>
	</fieldset>
	<fieldset>
		<h3>Datos de contacto</h3>
		<div>
			<label>Email de env&iacute;o: </label>
			<span><?
				$input = Core::getObject('Core_Html_Tag_Custom', 'input');
				$input
					->setType('text')
					->setMaxlength(300)
					->setId('email_contacto')
					->setName('anuncio[email_contacto]')
					->setValue($x->getEmailContacto())
					->setData('data-campo', '<b>Email</b>')
					->setData('data-validator', '{empty:false}')
				;
				echo $input->getHtml();
			?> 
			</span>
		</div>
	</fieldset>
	<div class="controls">
		<?php print Core::getObject('Core_Html_Tag_Custom', 'input')->settype('submit')->setValue('Guardar')->getHtml(); ?>
	</div>
</fieldset>
<script>
jQuery(document).ready(function(){
	jQuery('#id_tipo_contacto').change(function(){
		var desactivar = this.value=='1';
		jQuery('#label_contacto,#texto_contacto,#email_contacto').each(function(){
			jQuery(this).parents('div:first').setDisable(desactivar);
		});
	}).change();
});
function validar_agregar_anuncio_contacto(formData, jqForm, options) {
	if(!validar_estatico_en('#<?php print $id_fielset; ?>')){
		tabpanelfocus(jQuery('#<?php print $id_fielset; ?>'));
		return false;
	}
	return(true);
}
</script>