<?
if(!$this->hasObjectToEdit()){
	echo  ("no hay objeto a editar ".__FILE__.'-'.__LINE__);
	return;
}
$x = $this->getObjectToEdit();

$image_empty_src = $this->getSkinUrl('img/empty.gif');
$image_empty_size = 42;

?><?if($this->getIdToEdit()):?>
<input type="hidden" name="objetivo[id]" value="<?=$x->getId()?>" /><!-- si esta a cero o vacio es agregar --><?endif;?>
<fieldset id="<?php print $id_fielset = $this->generateRandomId(); ?>">
	<legend><?if(!$this->getIdToEdit()):?>Nuevo<?else:?>Editar<?endif;?> Objetivo</legend>
	<fieldset>
		<h3>Informacion de Objetivo</h3>
		<div>
			<label>Problemas Asociados: </label>
			<span><?
//				$problema = new Inta_Model_Problema();
//				$problemas = $problema->search();
				$problemas = $this->getProblemas();
				$html_select = '';
				foreach($problemas as $problema){
					$option = c(new Core_Html_Tag_Custom('option'))
						->setValue($problema->getId())
						->setInnerHtml($problema->getNombre())
					;
					if($problema->getIdObjetivo()==$x->getId())
						$option->setSelected('selected');
					$html_select .= $option->getHtml();
				}
				echo c(new Core_Html_Tag_Custom('select'))
					->setName('problemas_asociados[]')
					->setSize(15)
					->setMultiple('multiple')
					->setInnerHtml($html_select)
					->getHtml()
				;
			?> 
			</span>
			<div>
		</div>
		</div>
	</fieldset>
	<div class="controls">
		<input type="submit" value="Guardar"/>
	</div>
</fieldset>
<script>

jQuery(document).ready(function(){
	jQuery('#descripcion').ckeditor();
});

function validar_agregar_objetivo_datos(formData, jqForm, options) {
	if(!validar_estatico_en('#<?php print $id_fielset; ?>')){
		tabpanelfocus(jQuery('#<?php print $id_fielset; ?>'));
		return false;
	}
	return(true);
}
</script>