<?
if(!$this->hasObjectToEdit()){
	echo  ("no hay objeto a editar ".__FILE__.'-'.__LINE__);
	return;
}
$x = $this->getObjectToEdit();

?><?if($this->getIdToEdit()):?>
<input type="hidden" name="pagina[id]" value="<?=$x->getId()?>" /><!-- si esta a cero o vacio es agregar --><?endif;?>
<fieldset id="<?php print $id_fielset = $this->generateRandomId(); ?>">
	<legend><?if(!$this->getIdToEdit()):?>Nuevo<?else:?>Editar<?endif;?> Pagina</legend>
	<fieldset>
		<h3>Datos</h3>
		<div>
			<label>Nombre: </label>
			<span><?
				$input = Core::getObject('Core_Html_Tag_Custom', 'input');
				$input
					->setMaxlength(300)
					->setType('text')
					->setId('titulo')
					->setName('pagina[titulo]')
					->setValue($x->getTitulo())
					->setData('data-campo', '<b>Nombre</b>')
					->setData('data-validator', '{empty:false}')
				;
				echo $input->getHtml();
			?> 
			</span>
			<span><?
				echo c($input = Core::getObject('Core_Html_Tag_Custom', 'input'))
					->setType('hidden')
					->setName('pagina[titulo_interno]')
					->setValue('0')
					->getHtml();
				if($x->getData('titulo_interno')){
					$input->setChecked('checked');
				}
				echo $input
					->setType('checkbox')
					->setId('titulo_interno')
					->setValue('1')
					->getHtml()
				;
			?>	
			</span>
			<label for="titulo_interno" style="display:inline;">Usar como t&iacute;tulo interno</label>

			<label>Desarrollo: </label>
			<span><?
				$input = Core::getObject('Core_Html_Tag_Custom', 'textarea');
				$input
					//->setClass('ckeditor '.$desarrollo_class=md5(rand(1,1000)))
					->setType('text')
					->setId('contenido_html')
					->setName('pagina[contenido_html]')
					->setRows(20)
					->setCols(80)
					//->setValue($x->getNombre())
					//->setData('data-campo', '<b>Nombre</b>')
					//->setData('data-validator', '{empty:false}')
					->setInnerHtml(htmlentities(stripslashes($x->getContenidoHtml())))
				;
				echo $input->getHtml();
			?> 
			</span>
			<label>Nombre Interno: </label>
			<span><?
				$input = Core::getObject('Core_Html_Tag_Custom', 'input');
				$input
					->setMaxlength(300)
					->setType('text')
					->setId('nombre_interno')
					->setName('pagina[nombre_interno]')
					->setReadonly('readonly')
					->setValue($x->getNombreInterno())
					//->setData('data-campo', '<b>Nombre Interno</b>')
					//->setData('data-validator', '{empty:false}')
				;
				echo $input->getHtml();
			?> 
			</span>
		</div>
	</fieldset>
	<div class="controls">
		<?php print Core::getObject('Core_Html_Tag_Custom', 'input')->settype('submit')->setValue('Guardar')->getHtml(); ?>
	</div>
</fieldset>
<script>
jQuery(document).ready(function(){
	jQuery('#contenido_html').ckeditor({
			instanceReady:function(arg){
//				var child = window;
//				alert(window.parent.console);
//				console.log(jQuery('iframe'));
				var documentelement = jQuery('#contenido_html')[0].instanciaCkeditor.document.getDocumentElement().$;
				//window.console.log(jQuery('body', documentelement));
				jQuery('body', documentelement).addClass('nodo_pagina');
				var stylesheet_url = <?php print json_encode($this->getSkinUrl('css/ckeditor_reset.css')); ?>;
				var jqel = jQuery('<link rel="stylesheet" type="text/css" href="'+stylesheet_url+'" />');
				jQuery('head', documentelement).append(jqel);
				jqel = null;
				arg.editor.config.contentsCss = (stylesheet_url); 
				window.console.log(jqel);
				//jQuery('head', documentelement)
//				window.console.log();
//				with(window.parent){
//					
//					console.log("yey");
//					console.log(child.document.body);
//				}
				child = null;
				documentelement = null;
				//window.parent.window.console.log(jQuery('#cke_contents_editor1'));
			}
	});
})
function validar_agregar_pagina(formData, jqForm, options) {
	jQuery('#contenido_html').ckeditor('refresh');
	if(!validar({
		donde: '#<?php print $id_fielset; ?>',
		estatico:true})){
		//jQuery.ckeditor.refresh();
		return false;
	}
	return(true);
}
</script>