<?
if(!$this->hasObjectToEdit()){
	echo  ("no hay objeto a editar ".__FILE__.'-'.__LINE__);
	return;
}
$x = $this->getObjectToEdit();


?><?if($this->getIdToEdit()):?>
<input type="hidden" name="proyecto_actividad[id]" value="<?=$x->getId()?>" /><!-- si esta a cero o vacio es agregar --><?endif;?>
<input type="hidden" name="proyecto_actividad[id_actividad]" value="<?=$x->getIdActividad()?>" /> 
<fieldset id="<?php print $id_fielset = $this->generateRandomId(); ?>">
	<legend><?if(!$this->getIdToEdit()):?>Nuevo<?else:?>Editar<?endif;?> ProyectoActividad</legend>
	<fieldset>
		<h3>Informacion de ProyectoActividad</h3>
		<div>
			<label>Actividad: </label>
			<span><?
				$proyecto = new Inta_Model_Proyecto();
				$proyectos = $proyecto->search();
				$html_select = '';
				foreach($proyectos as $proyecto){
					$option = c(new Core_Html_Tag_Custom('option'))
						->setValue($proyecto->getId())
						->setInnerHtml($proyecto->getNombre())
					;
					if($proyecto->getId()==$x->getIdActividad())
						$option->setSelected('selected');
					$html_select .= $option->getHtml();
				}
				echo c(new Core_Html_Tag_Custom('select'))
					->setName('proyecto_actividad[id_proyecto]')
					->setId('id_proyecto')
					->setInnerHtml($html_select)
					->getHtml()
				;
			?> 
			</span>
			<div>
		</div>
		</div>
	</fieldset>
	<div class="controls">
		<input type="submit" value="Guardar"/>
	</div>
</fieldset>
<script>

function proyecto_actividad_enviado(responseText, statusText, xhr, $form){
	jQuery.ScreenBlock(false);
}

function validar_agregar_proyecto_actividad_datos(formData, jqForm, options) {
	if(!validar_estatico_en('#<?php print $id_fielset; ?>')){
		tabpanelfocus(jQuery('#<?php print $id_fielset; ?>'));
		return false;
	}
	return(true);
}
</script>