<form id="<?=$id=$this->generateRandomId(); //strtr($this->getNameInLayout(),array('.'=>'','#'=>''))?>" 
	<?if($this->hasEnctype()):?>
	enctype="<?=$this->getEnctype()?>"<?
	endif?>
	method="<?=$this->getMethod()?>" 
	action="<?=$this->getUrl($this->getActionUrl())?>"><?=$this->getChildHtml()?> 
	<input type='hidden' name='isajaxrequest' id='isajaxrequest' value='0' />
</form><?
if($this->hasValidadorJs()||Admin_App::getInstance()->getModoAjax()){
	$options = array(
		'target'=>$this->getAjaxTarget(),
	);
	if($this->hasAjaxReplaceWith()){
		$options['replaceWith'] = true;//esto es una modificacion del plugin jquery.form.js en linea 225
	}
//	if($this->hasSuccessJs()){
//		$options['success'] = $this->getSuccessJs();
//	}
?> 
<script>
	jQuery(document).ready(function(){
		try{
		<?
		if($this->hasValidadorJs()){
			if(!is_array($validadores = $this->getValidadorJs()))
				$validadores = explode(',', $validadores);
			foreach($validadores as $validator){?> 
		if(<?php print $validator; ?>!=null)
			jQuery('#<?php print $id; ?>').multivalidator(<?php print $validator; ?>);<?
			}
		}
		if($this->getAjaxMethod()=='ajaxSubmit'):?> 
		jQuery('#<?=$id?>').submit(function(){<?
		if(Admin_App::getInstance()->getModoAjax()){?> 
			var jqform = jQuery(this);
			jQuery('#<?php print $id; ?>').multivalidate(function(resultado){
				if(resultado){
					var options = <?=json_encode($options);?>;
					<?
		if($this->hasSuccessJs()){
			echo 'options.success = '.$this->getSuccessJs().";\n";
		}
		?> 
		//esto estaba mal, porque si un validador modifica los valores estos no se envian modificados con el beforeSubmit
		//			options.beforeSubmit = function(){
		//				return jQuery('#<?php print $id; ?>').multivalidate();
		//			}
					$("#isajaxrequest", this).attr("value", 1);
					jqform.ajaxSubmit(options);
				}
			});
			return(false);<?
		}
		else{?> 
			return jQuery('#<?php print $id; ?>').multivalidate();<?	
		}?> 
		
		});
		<?elseif($this->getAjaxMethod()=='ajaxForm'):?> 
		var options = <?=json_encode($options);?>;
		<?
		if($this->hasSuccessJs()){
			echo 'options.success = '.$this->getSuccessJs().";\n";
		}
		?> 
		options.beforeSubmit = function(){
			return jQuery('#<?php print $id; ?>').multivalidate();
		}; 
		$('#<?=$id?>').ajaxForm(options);
		<?endif?>
		}
		catch(e){
			alert(e);
		}
	});
</script>
<?	
}

?>