<?
$x = new Inta_Model_Agencia();
if($this->hasIdToEdit()){
	$x->setId($this->getIdToEdit());
	$x->load();
}
else{
	if(Core_Http_Post::hasParameters()){//si ya hizo post (cuando no se agrego/modifico y vuelve con errores)
		$x->loadFromArray(Core_Http_Post::getParameters('array'));
	}
}
$x->addAutofilterOutput('utf8_decode');
$image_empty_src = $this->getSkinUrl('img/empty.gif');
$image_empty_size = 42;

?><?if($this->getIdToEdit()):?>
<input type="hidden" name="agencia[id]" value="<?=$x->getId()?>" /><!-- si esta a cero o vacio es agregar --><?endif;?>
<fieldset id="<?php print $id_fielset = $this->generateRandomId(); ?>">
	<legend><?if(!$this->getIdToEdit()):?>Nuevo<?else:?>Editar<?endif;?> Agencia</legend>
	<fieldset>
		<h3>Informacion de Agencia</h3>
		<div>
			<label>Nombre: </label>
			<span><?
				$input = new Core_Html_Tag_Custom('input');
				$input
					->setMaxlength(300)
					->setType('text')
					->setId('nombre')
					->setName('agencia[nombre]')
					->setValue($x->getNombre())
					->setData('data-campo', '<b>Nombre</b>')
					->setData('data-validator', '{empty:false}')
				;
				echo $input->getHtml();
			?> 
			</span>
			<label>Direcci&oacute;n: </label>
			<span><?
				$input = new Core_Html_Tag_Custom('input');
				$input
					->setType('text')
					->setMaxlength(300)
					->setId('direccion')
					->setName('agencia[direccion]')
					->setValue($x->getDireccion())
					->setData('data-campo', '<b>Direcci&oacute;n</b>')
					->setData('data-validator', '{empty:false}')
				;
				echo $input->getHtml();
			?> 
			</span>
		</div>
	</fieldset>
	<fieldset>
		<h3>Datos de contacto</h3>
		<div>
			<label>Telefono: </label>
			<span><?
				$input = new Core_Html_Tag_Custom('input');
				$input
					->setType('text')
					->setMaxlength(300)
					->setId('telefono')
					->setName('agencia[telefono]')
					->setValue($x->getTelefono())
					->setData('data-campo', '<b>Telefono</b>')
					->setData('data-validator', '{empty:false}')
				;
				echo $input->getHtml();
			?> 
			</span>
			<label>Email: </label>
			<span><?
				$input = new Core_Html_Tag_Custom('input');
				$input
					->setType('text')
					->setMaxlength(300)
					->setId('email')
					->setName('agencia[email]')
					->setValue($x->getEmail())
					->setData('data-campo', '<b>Email</b>')
					->setData('data-validator', '{empty:false}')
				;
				echo $input->getHtml();
			?> 
			</span>
		</div>
	</fieldset>
	<div class="controls">
		<input type="submit" value="Guardar"/>
	</div>
</fieldset>
<script>

jQuery(document).ready(function(){

})
function validar_agregar_agencia(formData, jqForm, options) {
	if(!validar({
		donde: '#<?php print $id_fielset; ?>',
		estatico:true})){
		return false;
	}
	return(true);
}
</script>