<?
if(!$this->hasObjectToEdit()){
	echo  ("no hay objeto a editar ".__FILE__.'-'.__LINE__);
	return;
}
$x = $this->getObjectToEdit();

?><?if($this->getIdToEdit()):?>
<input type="hidden" name="audiencia[id]" value="<?=$x->getId()?>" /><!-- si esta a cero o vacio es agregar --><?endif;?> 
<fieldset id="<?php print $id_fielset = $this->generateRandomId(); ?>">
	<legend><?if(!$this->getIdToEdit()):?>Nuevo<?else:?>Editar<?endif;?> Audiencia</legend>
	<fieldset>
		<h3>Informacion de Audiencia</h3>
		<div>
			<label>Agencia: </label>
			<span><?
				$agencia = new Inta_Model_Agencia();
				$agencias = $agencia->search();
				$html_select = '';
				foreach($agencias as $agencia){
					$option = c(Core::getObject('Core_Html_Tag_Custom', 'option'))
						->setValue($agencia->getId())
						->setInnerHtml($agencia->getNombre())
					;
					if($agencia->getId()==$x->getIdAgencia())
						$option->setSelected('selected');
					$html_select .= $option->getHtml();
				}
				echo c(Core::getObject('Core_Html_Tag_Custom', 'select'))
					->setName('audiencia[id_agencia]')
					->setId('id_agencia')
					->setDisabled('disabled')
					->setInnerHtml($html_select)
					->getHtml()
				;
				
				$input = Core::getObject('Core_Html_Tag_Custom', 'input');
				$input
					->setMaxlength(300)
					->setType('hidden')
					->setId('nombre')
					->setName('audiencia[id_agencia]')
					->setValue($x->getIdAgencia())
				;
				echo $input->getHtml();
			?> 
			</span>
			<label>Tipo Audiencia: </label>
			<span><?
				echo c($selector_tipo_audiencia = $this->appendBlock('<selector_tipo_audiencia />'))
					->setSelectedValue($x->getIdTipoAudiencia())
					->void($selector_tipo_audiencia
						->getSelectControl()
							->setName('audiencia[id_tipo_audiencia]')
							->setId('id_responsable')
					)
					->toHtml()
				;
			?> 
			</span>
			<label>Nombre: </label>
			<span><?
				$input = Core::getObject('Core_Html_Tag_Custom', 'input');
				$input
					->setMaxlength(300)
					->setType('text')
					->setId('nombre')
					->setName('audiencia[nombre]')
					->setValue($x->getNombre())
					->setData('data-campo', '<b>Nombre</b>')
					->setData('data-validator', '{empty:false}')
				;
				echo $input->getHtml();
			?> 
			</span>
			<div>
		</div>
		</div>
	</fieldset>
	<div class="controls">
		<?php print Core::getObject('Core_Html_Tag_Custom', 'input')->settype('submit')->setValue('Guardar')->getHtml(); ?>
	</div>
</fieldset>
<script>

jQuery(document).ready(function(){

});

function validar_agregar_audiencia_datos(formData, jqForm, options) {
	if(!validar_estatico_en('#<?php print $id_fielset; ?>')){
		tabpanelfocus(jQuery('#<?php print $id_fielset; ?>'));
		return false;
	}
	return(true);
}
</script>