<?
if(!$this->hasObjectToEdit()){
	echo  ("no hay objeto a editar ".__FILE__.'-'.__LINE__);
	return;
}
$x = $this->getObjectToEdit();


?><?if($this->getIdToEdit()):?>
<input type="hidden" name="usuario_actividad[id]" value="<?=$x->getId()?>" /><!-- si esta a cero o vacio es agregar --><?endif;?>
<input type="hidden" name="usuario_actividad[id_actividad]" value="<?=$x->getIdActividad()?>" /> 
<fieldset id="<?php print $id_fielset = $this->generateRandomId(); ?>">
	<legend><?if(!$this->getIdToEdit()):?>Nuevo<?else:?>Editar<?endif;?> UsuarioActividad</legend>
	<fieldset>
		<h3>Informacion de UsuarioActividad</h3>
		<div>
			<label>Actividad: </label>
			<span><?
				$usuarios = c($usuario = new Inta_Model_Usuario())
                	->setIdAgencia(Admin_Helper::getInstance()->getIdAgencia())
                	->setWhere(Db_Helper::equal('id_agencia'))
                	->search()
				;
				$html_select = '';
				foreach($usuarios as $usuario){
					$option = c(new Core_Html_Tag_Custom('option'))
						->setValue($usuario->getId())
						->setInnerHtml($usuario->getNombre())
					;
					if($usuario->getId()==$x->getIdUsuario())
						$option->setSelected('selected');
					$html_select .= $option->getHtml();
				}
				echo c(new Core_Html_Tag_Custom('select'))
					->setName('usuario_actividad[id_usuario]')
					->setId('id_usuario')
					->setInnerHtml($html_select)
					->getHtml()
				;
			?> 
			</span>
			<div>
		</div>
		</div>
	</fieldset>
	<div class="controls">
		<input type="submit" value="Guardar"/>
	</div>
</fieldset>
<script>

function usuario_actividad_enviado(responseText, statusText, xhr, $form){
	jQuery.ScreenBlock(false);
}

function validar_agregar_usuario_actividad_datos(formData, jqForm, options) {
	if(!validar_estatico_en('#<?php print $id_fielset; ?>')){
		tabpanelfocus(jQuery('#<?php print $id_fielset; ?>'));
		return false;
	}
	return(true);
}
</script>