<script type="text/javascript">
	function ordenarEstadistica(elemento, id_estadistica){
		jQuery.blockUI({
			message: 'Cargando ordenador...<br /><center><div class="loading1"></div></center>'
		});
		jQuery.get(
			'<?php print $this->getUrl('administrator/ajax/estadistica/ordenar/'); ?>'+id_estadistica,
			function(data){
				var mensaje = jQuery(data);
				var jqcierra = jQuery('<input class="ordenando" type="button" value="cerrar" />').appendTo(mensaje);
				jqcierra.click(function(){
					getGrid(elemento).trigger("reloadGrid");
					jQuery.unblockUI();
				})
				jQuery.blockUI({
					message: mensaje,
					centerY:true
				});
			}
		);
	}
</script>