<?
if(!$this->hasObjectToEdit()){
	echo  ("no hay objeto a editar ".__FILE__.'-'.__LINE__);
	return;
}
$x = $this->getObjectToEdit();

$configcke1 = array(
	'config'=>array(
		'toolbar' => 'Basic',
		'toolbarStartupExpanded'=> false,
	)
);
$configcke2 = array(
	'config'=>array(
		'toolbar' => array(
		    array( 'Source', '-', 'Bold', 'Italic', 'Underline', 'Strike' ),
		    array( 'Image', 'Link', 'Unlink', 'Anchor' )
		),
		'toolbarStartupExpanded'=> false
	)
);
		

?><?if($this->getIdToEdit()):?>
<input type="hidden" name="actividad[id]" value="<?=$x->getId()?>" /><!-- si esta a cero o vacio es agregar --><?endif;?>
<fieldset id="<?php print $id_fielset = $this->generateRandomId(); ?>">
	<legend><?if(!$this->getIdToEdit()):?>Nuevo<?else:?>Editar<?endif;?> Actividad</legend>
	<fieldset>
		<h3>Informacion de Actividad</h3>
		<div>
            <label>Responsable: </label>
			<span><?
				echo c($selector_usuario = $this->appendBlock('<selector_usuario />'))
					->setSelectedValue($x->getIdResponsable())
					->void($selector_usuario
						->getSelectControl()
							->setName('actividad[id_responsable]')
							->setId('id_responsable')
					)
					->toHtml()
				;
			?> 
			</span>			
			<label>Nombre: </label>
			<span><?
				$input = Core::getObject('Core_Html_Tag_Custom', 'input');
				$input
					->setMaxlength(300)
					->setType('text')
					->setId('nombre')
					->setName('actividad[nombre]')
					->setValue($x->getNombre())
					->setData('data-campo', '<b>Nombre</b>')
					->setData('data-validator', '{empty:false}')
				;
				echo $input->getHtml();
			?>
			</span>
			<label>A&ntilde;o: </label>
			<span><?
				$input = Core::getObject('Core_Html_Tag_Custom', 'input');
				$input
					->setMaxlength(300)
					->setType('text')
					->setId('ano')
					->setName('actividad[ano]')
					->setValue($x->getAno())
					->setData('data-campo', '<b>Año</b>')
					->setData('data-validator', '{empty:false,entero:4}')
				;
				echo $input->getHtml();
			?>
			</span>
			<label>Porcentaje Cumplimiento: <?
				$input = Core::getObject('Core_Html_Tag_Custom', 'input');
				$input
					->setMaxlength(300)
					->setType('text')
					->setId('porcentaje_cumplimiento')
					->setReadonly('readonly')
					->setName('actividad[porcentaje_cumplimiento]')
					->setStyle('border: 0pt none; color: rgb(246, 147, 31); font-weight: bold;')
					->setValue($x->getPorcentajeCumplimiento())
					->setData('data-campo', '<b>Porcentaje Cumplimiento</b>')
					->setData('data-validator', '{empty:false,porcentaje:true}')
				;
				echo $input->getHtml();
			?></label>
			<span>
			<div class="slider" data-info="<?php print htmlentities(json_encode(array('target'=>'#porcentaje_cumplimiento', 'min'=>0,'max'=>100, 'step'=>10, 'fixed'=>2))); ?>"></div>
			</span>
			<label>Porcentaje Tiempo: <?
				$input = Core::getObject('Core_Html_Tag_Custom', 'input');
				$input
					->setMaxlength(300)
					->setType('text')
					->setId('porcentaje_tiempo')
					->setReadonly('readonly')
					->setName('actividad[porcentaje_tiempo]')
					->setStyle('border: 0pt none; color: rgb(246, 147, 31); font-weight: bold;')
					->setValue($x->getPorcentajeTiempo())
					->setData('data-campo', '<b>Porcentaje Tiempo</b>')
					->setData('data-validator', '{empty:false,porcentaje:true}')
				;
				echo $input->getHtml();
			?></label>
			<span>
				<div class="slider" data-info="<?php print htmlentities(json_encode(array('target'=>'#porcentaje_tiempo', 'min'=>0,'max'=>100, 'step'=>10, 'fixed'=>2))); ?>"></div>
			</span>
			<label>Presupuesto Estimado: </label>
			<span><?
				$input = Core::getObject('Core_Html_Tag_Custom', 'input');
				$input
					->setMaxlength(300)
					->setType('text')
					->setId('presupuesto_estimado')
					->setName('actividad[presupuesto_estimado]')
					->setValue($x->getPresupuestoEstimado())
					->setData('data-campo', '<b>Presupuesto Estimado</b>')
//					->setData('data-validator', '{empty:false,decimal:2}')
				;
				echo $input->getHtml();
			?>
			</span>
			<label>Estado: </label>
			<span><?
				$select = Core::getObject('Core_Html_Tag_Custom', 'select');
                                $select
                                        ->setId('estado')
                                        ->setName('indicador[estado]')
                                ;
                                $html = '';
                                $aOptions = array('planificado' => 'Planificado','cancelado' => 'Cancelado', 'realizado' => 'Realizado');
                                foreach($aOptions As $key => $value){
                                    $option = Core::getObject('Core_Html_Tag_Custom', 'option');
                                    $option
                                            ->setValue($key)
                                            ->setInnerHtml($value)
                                    ;
                                    if($x->getEstado()==$key)
                                            $option->setSelected('selected');
                                    $html .= $option->getHtml();
                                }
                                $select->setInnerHtml($html);
				echo $select->getHtml();
			?>
			</span>
		</div>
	</fieldset>
	<fieldset>
		<h3>Informacion de Actividad</h3>
		<div>
			<label>Observaciones: </label>
			<span><?
				$input = Core::getObject('Core_Html_Tag_Custom', 'textarea');
				$input
					->setId('observaciones')
					->setName('actividad[observaciones]')
					->setInnerHtml(htmlentities($x->getObservaciones()))
                                        ->setRows(5)
                                        ->setCols(40)
//					->setData('data-campo', '<b>Observaciones</b>')
//					->setData('data-validator', '{empty:false}')
//                                        ->setData('data-mensaje', 'Debe cargar uno o mas %field separados por comas')
				;
				echo $input->getHtml();
			?>
			</span><?{/** /?> 
			<label>Comentarios: </label>
			<span><?
				$input = Core::getObject('Core_Html_Tag_Custom', 'textarea');
				$input
					->setId('comentario')
					->setName('actividad[comentario]')
					->setInnerHtml(htmlentities($x->getComentario()))
                                        ->setRows(5)
                                        ->setCols(40)
//					->setData('data-campo', '<b>Comentarios</b>')
//					->setData('data-validator', '{empty:false}')
//                                        ->setData('data-mensaje', 'Debe cargar uno o mas %field separados por comas')
				;
				echo $input->getHtml();
			?>
			</span><?/**/}?>
		</div>
	</fieldset>
	<div class="controls">
		<?php print Core::getObject('Core_Html_Tag_Custom', 'input')->settype('submit')->setValue('Guardar')->getHtml(); ?>
	</div>
</fieldset>
<script>
jQuery(document).ready(function(){
	jQuery('#observaciones').ckeditor(<?php print json_encode( $configcke1 ); ?>);
	jQuery('#comentario').ckeditor(<?php print json_encode($configcke1); ?>);
    jQuery('input[type=button][value=Agregar]').live('click',function(){
//        jQuery(this).parents('div').eq(0).clone().appendTo(jQuery(this).parents('fieldset').eq(0));
        var x = jQuery(this).parents('div').eq(0).clone();
        jQuery(x).appendTo(jQuery(this).parents('fieldset').eq(0));
        jQuery('input[type=button][value=Eliminar]',x).css('display','inline');
    });
    jQuery('input[type=button][value=Eliminar]').live('click',function(){
        jQuery(this).parents('div').eq(0).remove();
    });
    jQuery('.slider').each(function(){
    	jQuery(this).css('margin-top', '9px');
		var data = jQuery(this).attr('data-info');
		var options = null;
		try{
			eval('options='+data);
		}
		catch(e){
			alert("kradkk");
			return;
		}
		options.value = jQuery(options.target).val();
		options.slide = function(event, ui){
			var val = ui.value;
			if(options.fixed){
				val = (new Number(parseFloat(val))).toFixed(options.fixed);
			}
			jQuery(options.target).val(val);
		}
		jQuery(this).slider(options);
		//jQuery(options.target).val(ui.value);
	})
	//$("#amount").val('$' + $("#slider").slider("value"));

});
function validar_agregar_actividad(formData, jqForm, options) {
	if(!validar({
		donde: '#<?php print $id_fielset; ?>',
		estatico:true})){
		return false;
	}
	return(true);
}
</script>