<?
if(!$this->hasObjectToEdit()){
	echo  ("no hay objeto a editar ".__FILE__.'-'.__LINE__);
	return;
}
$x = $this->getObjectToEdit();

?><?if($this->getIdToEdit()):?>
<input type="hidden" name="actividad[id]" value="<?=$x->getId()?>" /><!-- si esta a cero o vacio es agregar --><?endif;?>
<fieldset id="<?php print $id_fielset = $this->generateRandomId(); ?>">
	<legend><?if(!$this->getIdToEdit()):?>Nuevo<?else:?>Editar<?endif;?> Actividad</legend>
	<fieldset>
            <h3>Cronograma</h3>
            <div><?php
            $meses = array(
            	array(
            		'name'=>'mes_enero',
            		'label'=>'Enero',
				),
            	array(
            		'name'=>'mes_febrero',
            		'label'=>'Febrero',
				),
            	array(
            		'name'=>'mes_marzo',
            		'label'=>'Marzo',
				),
            	array(
            		'name'=>'mes_abril',
            		'label'=>'Abril',
				),
            	array(
            		'name'=>'mes_mayo',
            		'label'=>'Mayo',
				),
            	array(
            		'name'=>'mes_junio',
            		'label'=>'Junio',
				),
            	array(
            		'name'=>'mes_julio',
            		'label'=>'Julio',
				),
            	array(
            		'name'=>'mes_agosto',
            		'label'=>'Agosto',
				),
            	array(
            		'name'=>'mes_septiembre',
            		'label'=>'Septiembre',
				),
            	array(
            		'name'=>'mes_octubre',
            		'label'=>'Octubre',
				),
            	array(
            		'name'=>'mes_noviembre',
            		'label'=>'Noviembre',
				),
            	array(
            		'name'=>'mes_diciembre',
            		'label'=>'Diciembre',
				),
			);
			foreach($meses as $data){
				$mes = new Core_Object($data);?>
				<span style="float:left;margin:4px 2px 0 0;"> 
                    <?
//                            $input = Core::getObject('Core_Html_Tag_Custom', 'input');
//                            $input
//                                    ->setType('checkbox')
//                                    ->setId('mes_enero')
//                                    ->setName('actividad[mes_enero]')
//                                    ->setValue(1)
//                            ;
//                            if($x->getMesEnero())
//                                $input->setChecked($x->getMesEnero('on'));
//                            echo $input->getHtml();
                            
							echo c($input = Core::getObject('Core_Html_Tag_Custom', 'input'))
								->setType('hidden')
								->setName('actividad['.$mes->getName().']')
								->setValue('0')
								->getHtml();
							if($x->getData($mes->getName())){
								$input->setChecked('checked');
							}
							echo $input
								->setType('checkbox')
								->setId($mes->getName())
								->setValue('1')
								->getHtml()
							;
                    ?></span>
                    <label style="cursor:pointer;margin-bottom:3px;white-space:nowrap;" for="<?php print $mes->getName(); ?>"><?php print $mes->getLabel(); ?></label>
                    <?php
				}?> 
            </div>
	</fieldset>
	<div class="controls">
		<?php print Core::getObject('Core_Html_Tag_Custom', 'input')->settype('submit')->setValue('Guardar')->getHtml(); ?>
	</div>
</fieldset>
<script>

jQuery(document).ready(function(){
//    jQuery('input[type=submit]').unbind('click');
//    $('input[type=submit]').bind('click', function() {
//      //jQuery('input[type=checkbox][#^=mes]:not(:checked)').val(0).attr('checked','true');
//    });
})
</script>