				<div class="contenedor_banner_dinamico s_1x1">
                    <img src="<?php echo $this->getSkinUrl("img/publicidad_abajo.jpg") ?>"/>
                </div>
                <div class="contenedor_banner_dinamico s_1x1">
                    <img src="<?php echo $this->getSkinUrl("img/publicidad_abajo.jpg") ?>"/>
                </div>
                <div class="contenedor_banner_dinamico s_1x1">
                    <img src="<?php echo $this->getSkinUrl("img/publicidad_abajo.jpg") ?>"/>
                </div>
                <div class="contenedor_banner_dinamico s_1x1 last">
                    <img src="<?php echo $this->getSkinUrl("img/publicidad_abajo.jpg") ?>"/>
                </div>
                <div style="clear: both;"/>