<?
if(!$this->hasObjectToEdit()){
	echo  ("no hay objeto a editar ".__FILE__.'-'.__LINE__);
	return;
}
$x = $this->getObjectToEdit();


?><?if($this->getIdToEdit()):?>
<input type="hidden" name="aspecto_actividad[id]" value="<?=$x->getId()?>" /><!-- si esta a cero o vacio es agregar --><?endif;?>
<input type="hidden" name="aspecto_actividad[id_actividad]" value="<?=$x->getIdActividad()?>" /> 
<fieldset id="<?php print $id_fielset = $this->generateRandomId(); ?>">
	<legend><?if(!$this->getIdToEdit()):?>Nuevo<?else:?>Editar<?endif;?> AspectoActividad</legend>
	<fieldset>
		<h3>Informacion de AspectoActividad</h3>
		<div>
			<label>Actividad: </label>
			<span><?
				$aspecto = new Inta_Model_Aspecto();
				$aspectos = $aspecto->search();
				$html_select = '';
				foreach($aspectos as $aspecto){
					$option = c(new Core_Html_Tag_Custom('option'))
						->setValue($aspecto->getId())
						->setInnerHtml($aspecto->getNombre())
					;
					if($aspecto->getId()==$x->getIdActividad())
						$option->setSelected('selected');
					$html_select .= $option->getHtml();
				}
				echo c(new Core_Html_Tag_Custom('select'))
					->setName('aspecto_actividad[id_aspecto]')
					->setId('id_aspecto')
					->setInnerHtml($html_select)
					->getHtml()
				;
			?> 
			</span>
			<label>Detalle: </label>
			<span><?
				$input = new Core_Html_Tag_Custom('input');
				$input
					->setMaxlength(300)
					->setType('text')
					->setId('nombre')
					->setName('aspecto_actividad[nombre_extendido]')
					->setValue($x->getNombreExtendido())
//					->setData('data-campo', '<b>Detalle</b>')
//					->setData('data-validator', '{empty:false}')
				;
				echo $input->getHtml();
			?> 
			</span>
			<div>
		</div>
		</div>
	</fieldset>
	<div class="controls">
		<input type="submit" value="Guardar"/>
	</div>
</fieldset>
<script>

function aspecto_actividad_enviado(responseText, statusText, xhr, $form){
	jQuery.ScreenBlock(false);
}

function validar_agregar_aspecto_actividad_datos(formData, jqForm, options) {
	if(!validar_estatico_en('#<?php print $id_fielset; ?>')){
		tabpanelfocus(jQuery('#<?php print $id_fielset; ?>'));
		return false;
	}
	return(true);
}
</script>